"$schema" = "node_modules/wrangler/config-schema.json"
name = "zennnmind"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-11"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".output/public"

[observability]
enabled = true

[vars]
VITE_APP_URL = "https://zennn.dev"
VITE_NODE_ENV = "production"

# [[kv_namespaces]]
# binding = "CACHE"
# id = "<Your KV ID>"