name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # Set production environment variables
      VITE_APP_URL: ${{ secrets.VITE_APP_URL || 'https://zennn.dev' }}
      VITE_NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate route tree
        run: bunx tsr generate

      - name: Create production environment file
        run: |
          echo "VITE_APP_URL=${{ env.VITE_APP_URL }}" > .env.production
          echo "VITE_NODE_ENV=${{ env.VITE_NODE_ENV }}" >> .env.production
          echo "Created .env.production with:"
          cat .env.production

      - name: Build blog data
        run: bun run build:blog

      - name: Build with TanStack Start
        run: bun run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy 